import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
 
const inter = Inter({ subsets: ["latin"] });
 
export const metadata: Metadata = {
    title: "Final Project",
    description: "Generated by create next app",
};
 
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} `}>
                <div className=" flex-row bg-green-100 text-black min-h-screen">
                {children}
                </div>
            </body>
        </html>
    );
}